name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test

      - name: install requirements
        run: >-
          conda install -c conda-forge --file requirements/build.txt --file requirements/run.txt --file requirements/test.txt --quiet --yes

      - name: install the package
        run: python -m pip install . --no-deps

      - name: run the tests and check for test coverage
        run: coverage run -m pytest diffpy/pdfmorph/tests --showlocals

      - name: generate test coverage report and upload to codecov
        run: |
          coverage report -m
          bash <(curl -s https://codecov.io/bash)

      - name: check code style
        run: flake8 .
